// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using learnpoint_test_consoleApp.Data;

namespace learnpoint_test_consoleApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211210211525_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("learnpoint_test_consoleApp.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resource");
                });

            modelBuilder.Entity("learnpoint_test_consoleApp.Entities.Resource", b =>
                {
                    b.OwnsOne("learnpoint_test_consoleApp.Entities.Resource+ExternalId", "SourceId", b1 =>
                        {
                            b1.Property<Guid>("ResourceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("GuidId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("IType")
                                .HasColumnType("int");

                            b1.Property<int>("IntId")
                                .HasColumnType("int");

                            b1.Property<int>("SType")
                                .HasColumnType("int");

                            b1.HasKey("ResourceId");

                            b1.ToTable("Resource");

                            b1.WithOwner()
                                .HasForeignKey("ResourceId");
                        });

                    b.OwnsOne("learnpoint_test_consoleApp.Entities.Resource+ExternalId", "TargetId", b1 =>
                        {
                            b1.Property<Guid>("ResourceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("GuidId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("IType")
                                .HasColumnType("int");

                            b1.Property<int>("IntId")
                                .HasColumnType("int");

                            b1.Property<int>("SType")
                                .HasColumnType("int");

                            b1.HasKey("ResourceId");

                            b1.ToTable("Resource");

                            b1.WithOwner()
                                .HasForeignKey("ResourceId");
                        });

                    b.Navigation("SourceId");

                    b.Navigation("TargetId");
                });
#pragma warning restore 612, 618
        }
    }
}
